### ISSUE TITLE
trouble with transmissionloss() and bellhop propagation model

### ISSUE THREAD

**Issue by elaprime** [org-arl/UnderwaterAcoustics.jl#28] opened 2021-07-19 23:03 UTC
I'm working on developing a propagation model for some bathymetry and speed of sound data. I copied and pasted the example for the Bellhop model from the documentation into Julia, and it worked, but the plots are not consistent.

my julia example : 
![image](https://user-images.githubusercontent.com/87676977/126237398-bb18addb-e7ab-4a30-81f8-87b1e730b288.png)

example on documentation : 
![image](https://user-images.githubusercontent.com/87676977/126237428-3cf6dc61-ceca-4b87-a5d9-f2c6e0642bc5.png)

The copied and pasted code :

```
using UnderwaterAcoustics
using Plots

env = UnderwaterEnvironment(
    seasurface = Vacuum,
    seabed = SandyClay,
    ssp = SampledSSP(0.0:20.0:40.0, [1540.0, 1510.0, 1520.0], :smooth),
    bathymetry = SampledDepth(0.0:50.0:100.0, [40.0, 35.0, 38.0], :linear)
)

pm = Bellhop(env; gaussian=true)
tx = AcousticSource(0.0, -5.0, 1000.0)
rx = AcousticReceiverGrid2D(1.0, 0.1, 1000, -40.0, 0.2, 200)
x = transmissionloss(pm, tx, rx)
Plots.plot(env; receivers=rx, transmissionloss=x)
```

I am concerned about this because of another error I'm getting in the model I'm working on writing right now. When trying to set up the environment, I am attempting to read in an array for the depth and speed sound data into the SampledSSP() method. It allows me to set up the environment, but when I try to compute the transmission loss I get the following error:

```
Bellhop said:
  Fortran runtime error: Bad real number in item 1 of list input
  
  Error termination. Backtrace:
  
  Could not print backtrace: libbacktrace could not find executable to open
  #0  0xffffffff
  org-arl/UnderwaterAcoustics.jl#1  0xffffffff
  org-arl/UnderwaterAcoustics.jl#2  0xffffffff
  org-arl/UnderwaterAcoustics.jl#3  0xffffffff
  org-arl/UnderwaterAcoustics.jl#4  0xffffffff
  org-arl/UnderwaterAcoustics.jl#5  0xffffffff
  org-arl/UnderwaterAcoustics.jl#6  0xffffffff
  org-arl/UnderwaterAcoustics.jl#7  0xffffffff
  org-arl/AcousticRayTracers.jl#7  0xffffffff
  org-arl/AcousticRayTracers.jl#6  0xffffffff
  org-arl/AcousticRayTracers.jl#5  0xffffffff
  org-arl/UnderwaterAcoustics.jl#11  0xffffffff
  org-arl/UnderwaterAcoustics.jl#12  0xffffffff
  org-arl/AcousticsToolbox.jl#5  0xffffffff
  org-arl/AcousticRayTracers.jl#4  0xffffffff

```
_________________________________________________________________________________________

My code : 

```
using UnderwaterAcoustics
using Plots
using NetCDF
using GeoArrays
using GeographicLib



depth2 = ncread("")
ss2 = ncread("")
lat = ncread("")
lon = ncread("")

depth3 = -depth2
depth4 = reverse(depth3)
bathy = GeoArrays.read("")
)


line = GeodesicLine(lon[12], lat[12], azi=0, dist=73152)
wpts = waypoints(line, dist=914.4)


depths = []
ranges = []
runningRange = 0
idx = []


for pnt in wpts
    idx = indices(bathy, [160.0,5.0])
    bathyVector = bathy[idx[1],idx[1]]
    bathy2 = bathyVector[1]
    if bathy2 === missing
        bathy2 = 0
    end
    bathy2 = abs(bathy2)
    push!(depths, bathy2)
    push!(ranges, runningRange)
    runningRange += 914.4
end
    

println(size(ranges), size(depths))    



env = UnderwaterEnvironment(
    seasurface = Vacuum,
    seabed = SandyClay,
    ssp = SampledSSP(depth4, ss2[1,1,:,1], :linear),
    bathymetry = SampledDepth(ranges, depths, :linear))

pm = Bellhop(env, gaussian=true)
tx = AcousticSource(0.0,-5.0,1000.0)
rx = AcousticReceiverGrid2D(1.0,0.1,1000, -40.0,0.2,200)
x = transmissionloss(pm,tx,rx)
Plots.plot(env; receivers=rx,transmissionloss=x)
```

Could anybody help me in identifying how to go about resolving this error?

**Comment by mchitre** [comment] 2021-07-20 06:21
Strange. I just ran the copy-pasted code and I get the plot in the correct orientation. What version of `Plots` are you on?

You can also check that the transmission loss output `x` is correctly oriented:
```
julia> x = transmissionloss(pm, tx, rx)
1000×200 Matrix{Float32}:
 Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf      …  12.7065  14.0883  14.1162  14.252   15.7287  17.27    17.0453  17.1546  18.9392
 Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf         12.6068  14.3773  14.1671  13.9933  15.6722  17.7871  17.2085  16.9233  18.9853
 Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf         12.4894  14.5895  14.1234  13.6997  15.5425  18.1774  17.2531  16.6478  18.9174
 Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf      Inf         12.4672  14.8542  14.1183  13.5168  15.5327  18.6668  17.3662  16.4985  18.9517
 83.8563  83.327   82.8019  82.2811  81.7646  81.2523  80.7443  80.2406  79.7411     12.5041  15.1396  14.0669  13.3509  15.5771  19.1879  17.4207  16.3625  19.021
 78.7527  78.2099  77.6714  77.1372  76.6073  76.0816  75.5604  75.0434  74.5307  …  12.5994  15.4287  13.9841  13.2128  15.668   19.7327  17.4394  16.2447  19.102
 75.9064  75.3531  74.8039  74.259   73.7183  73.1817  72.6494  72.1213  71.5974     12.7634  15.6786  13.879   13.1282  15.8212  20.2512  17.4311  16.172   19.215
 73.6163  73.0502  72.488   71.9296  71.375   70.8244  70.2775  69.7346  69.1955     12.999   15.9252  13.7441  13.0631  16.0347  20.8074  17.3774  16.1001  19.3495
 72.1496  71.6032  71.046   70.4924  69.9425  69.3962  68.8537  68.3147  67.7795     13.2888  16.1524  13.6115  13.0253  16.2798  21.3817  17.3233  16.0377  19.4598
  ⋮                                            ⋮                                  ⋱                                       ⋮                                  
 47.3121  47.4368  47.6233  47.8584  48.1212  48.3877  48.6316  48.8396  49.0103     49.8321  49.7892  49.8081  49.8945  50.0402  50.219   50.4011  50.5566  50.6657
 47.3586  47.4861  47.6699  47.8977  48.1507  48.4076  48.645   48.8528  49.0311     49.8207  49.7723  49.7892  49.8762  50.0245  50.2074  50.3944  50.5552  50.6689
 47.4053  47.5337  47.713   47.9324  48.1753  48.4236  48.6563  48.8666  49.0549     49.8108  49.7573  49.772   49.8591  50.0093  50.1954  50.3867  50.5522  50.6706
 47.4516  47.5788  47.752   47.9621  48.1953  48.4361  48.6662  48.8813  49.0825  …  49.8024  49.7441  49.7565  49.8432  49.9944  50.1829  50.3777  50.5477  50.6708
 47.4966  47.6208  47.7866  47.987   48.211   48.4459  48.6757  48.8981  49.1148     49.7957  49.7327  49.7427  49.8284  49.98    50.17    50.3676  50.5415  50.6694
 47.5397  47.6591  47.8164  48.0071  48.2228  48.4537  48.6855  48.9179  49.1528     49.7907  49.7233  49.7305  49.8148  49.9658  50.1565  50.3562  50.5338  50.6665
 47.5802  47.6932  47.8414  48.0227  48.2315  48.4604  48.6968  48.9418  49.1973     49.7874  49.7159  49.7201  49.8022  49.9519  50.1425  50.3437  50.5245  50.662
 47.6174  47.7228  47.8616  48.0341  48.2376  48.4668  48.7104  48.9705  49.2489     49.7859  49.7103  49.7113  49.7907  49.9383  50.128   50.33    50.5137  50.6561
```
is what you should get.

**Comment by mchitre** [comment] 2021-07-20 06:37
Your code doesn't run. `ncread()` fails, as there are only 2 methods for that function, none of which match the call signature you have:
```
julia> depth2 = ncread("")
ERROR: MethodError: no method matching ncread(::String)
Closest candidates are:
  ncread(::AbstractString, ::AbstractString; start, count) at /Users/mandar/.julia/packages/NetCDF/QftOe/src/NetCDF.jl:1046
  ncread(::AbstractString, ::AbstractString, ::Vector{T}, ::Vector{T}) where T<:Integer at /Users/mandar/.julia/packages/NetCDF/QftOe/src/NetCDF.jl:1063
```
Also you seem to have an unmatched `)` hanging around on line 17.

So I couldn't run your code to check, but I suspect that your `SampledSSP` or `SampledDepth` has `NaN` or `Inf` somewhere. And that causes Bellhop to choke.

---
### Guide to debugging:

You could print the `depth4`, `ss2`, `depths`, and `ranges` variables out to check. 

Alternatively, you can add `debug=true` to Bellhop to get it to retain the input/output files for you to manually check the files:
```
pm = Bellhop(env, gaussian=true, debug=true)
```
Then when you run the propagation model, you should get something like:
```
[ Info: Bellhop run completed in /var/folders/d5/wwnqgqpj13s503lrdb4pp0680000gn/T/bellhop_T68u9T, press ENTER to delete intermediate files...
```
You can manually check the files in the folder specified:
```
» cd /var/folders/d5/wwnqgqpj13s503lrdb4pp0680000gn/T/bellhop_T68u9T
» ls
model.bty
model.env
model.prt
model.shd
output.txt
```
Checking these files might give you a clearer picture of the error.

**Comment by elaprime** [comment] 2021-07-20 12:14
`using NetCDF` allows you to run `ncread()`, and that's all working fine, I just removed the file location from the code I pasted. I can't get `transmissionloss()` to run at all, that's where the error occurs.  Also, I just tried the `debug=true` and it's still giving me the same error. Everything else is working correctly. I've already checked all the variables, I just can't see the values for ssp and bathymetry and I'm not sure how to access them from the environment. `depths` and `ranges` contain all real numbers, so that's not a problem as far as i know. I think that extra parenthesis is just an error from the way I copied and pasted the code, because I had taken some comments out. When I run the code on my end, I don't get any errors for the parentheses. As far as plotting is concerned, I'm just using the package that is added when you use `pkg> add Plots`, so I'm not sure what's up with that. 

When I try to access the file output from debugging the Bellhop model, my computer says it can't find it. So I'm kind of at a loss right now because I don't know where it would be.

**Comment by mchitre** [comment] 2021-07-20 13:25
To check what versions of things you're running, go to REPL and press "]". That'll take you to package mode. Type "st" to get a list of installed packages with version numbers. That would be useful for me to reproduce your setup.

As far as the error when running your code is concerned, either you need to check the variables/files (see below) or you need to post standalone code that I can run and reproduce your problem. The code can't depend on files you have on your computer. I'd suggest creating a simple minimum working example (MWE) that reproduces the problem, and posting that.

If you want to debug it yourself, I'd suggest logging the variables and checking. And then checking the BELLHOP input files by using `debug=true` while creating the `Bellhop()` model. When you run `transmissionloss()`, you should get a folder name printed in your REPL. Don't press ENTER -- that will delete the files. In another terminal go to that folder and check the files -- if you need help with those, zip up the files and post them here. Once you're done, you can return to your REPL and press ENTER to delete the files.

**Comment by apatlpo** [comment] 2021-07-20 13:32
apologizes for intruding this issue @mchitre !
I see very useful tips for debugging here.
Even though they are not specific to the library, having these as part of the doc would be useful I think (in a debugging specific section for example with pointers to external material if need be)
This would avoid repeating these same tips in every single issue

**Comment by elaprime** [comment] 2021-07-20 13:33
My concern at this point is that I can't find the file when I copy the path and paste it into the File Explorer. It just says that there is nothing there. I'm running v1.6.1 of Julia.

**Comment by mchitre** [comment] 2021-07-20 13:39
@apatlpo agree, will update docs to provide troubleshooting info in the next update.

@elaprime:
1. Julia version is useful, but I'll need exact versions of all packages installed to reproduce your problem. So you need to follow the steps to get a list of packages with versions.
2. Also, either I need a MWE or the log files, otherwise I have no information to work from to debug your problem. Make sure you don't press ENTER when you see the log message -- that deletes the files. Navigate to the folder manually if the copy-n-paste doesn't work. Be mindful of differences between Windows/Linux/OSX path with "\" or "/" and adjust as needed.

**Comment by elaprime** [comment] 2021-07-20 13:43
Okay, I see. I'm using Plots v1.15.2. I honestly don't know what an MWE is :/ I'm very new to this and my computer skills are lacking. 

The packages/versions I have are below. 
  [c52e3926] Atom v0.12.32    
  [b4f34e82] Distances v0.10.3
  [7a1cc6ca] FFTW v1.4.1      
  [5789e2e9] FileIO v1.10.1
  [5752ebe1] GMT v0.35.0
  [7073ff75] IJulia v1.23.2
  [916415d5] Images v0.24.1
  [e5e0dc1b] Juno v0.8.4
  [23992714] MAT v0.10.1
  [30363a11] NetCDF v0.11.3
  [3725be50] PhysOcean v0.6.3 `https://github.com/gher-ulg/PhysOcean.jl.git#master`
  [14b8a8f1] PkgTemplates v0.7.16
  [91a5bcdd] Plots v1.15.2
  [0efb1f7a] UnderwaterAcoustics v0.1.1
  [1986cc42] Unitful v1.8.0
  [8dfed614] Test

 [c9ce4bd3] ArchGDAL v0.6.0
  [add2ef01] GDAL v1.2.2
  [2fb1d81b] GeoArrays v0.4.0
  [a4aa24f8] GeoEstimation v0.7.2
  [c96ba436] GeographicLib v0.4.1 `https://github.com/anowacki/GeographicLib.jl.git#master`
  [916415d5] Images v0.24.1
  [14b8a8f1] PkgTemplates v0.7.17

**Comment by mchitre** [comment] 2021-07-20 13:52
Sorry for the jargon. MWE (Minimum Working Example) was described in my post above. Essentially a self-contained piece of code that I can run to reproduce your problem. Ideally, as simple as possible, but more importantly, not depending on something that is only on your computer.

Thanks for the list of packages. I see you are working with a quite old version of Plots (current version is 1.19.2). While this should not be the reason for the inverted plot, it might be worth testing it with the latest Plots package. You can upgrade by typing "up Plots" in the package mode (press "]" in REPL to go into package mode).

P.S. I also notice that you're using Atom. Do note that the Atom plugin is outdated and no longer maintained. The Julia community has moved to VSCode as the IDE of choice. Again, I don't think this is the reason for the inverted plot, but worth keeping in mind if you come across problems, especially related to plotting, etc.

**Comment by elaprime** [comment] 2021-07-20 13:57
I updated Plots, but I'm still getting the same upside down plot for the example that's working (the one that allows me to use  `transmissionloss()`) but in my main code that I'm working on, I still get the error trying to use that function. From looking at those files, it appears that everything is set up correctly, but I'm not exactly sure how to troubleshoot that in depth.

**Comment by mchitre** [comment] 2021-07-20 14:01
I'd suggest pasting the exact code you're running here. And also all the full program output when you run it. Because there may be details in there that I might be able to see to help diagnose the problem.

**Comment by mchitre** [comment] 2021-07-20 14:13
Thanks. That is helpful. And you don't see anything in the `C:\Users\Emily\AppData\Local\Temp\bellhop_BeDIRN` folder? No files? Does the folder exist? Do note that the folder name will change every run. Remember to check before pressing ENTER.

**Comment by elaprime** [comment] 2021-07-20 14:27
Yes I found those files! Woohoo! I am holding on the debug statement right now (not pressing ENTER) because I don't know where to go from here to check things out.

**Comment by mchitre** [comment] 2021-07-20 15:02
Fantastic. Take a look at the files to see if you can find the problem. If not, zip up the files and post here and I can help take a look.

**Comment by elaprime** [comment] 2021-07-20 15:41
I can't figure out the error. The output is empty because it's technically still in debug mode, I guess. I still haven't pressed ENTER to end that. I have attached the files below. Thank you for all of your assistance. 


[model.zip](https://github.com/org-arl/UnderwaterAcoustics.jl/files/6849599/model.zip)

**Comment by mchitre** [comment] 2021-07-20 16:23
@elaprime The files you attached are for the run when you ran the example from the documentation, not for the time you ran your own code. This run was successful. Could you try the same steps for your code please?

**Comment by elaprime** [comment] 2021-07-20 16:25
That is what I got when I ran from my own code. The example works fine. I didn't want to press ENTER for the run with my code because I didn't want the files to get deleted.

**Comment by elaprime** [comment] 2021-07-20 16:30
Now I'm just even more confused, because it did run this time when I just reran it, and I didn't change anything. But the plot I'm getting has the same issue of the source being at the position of the receiver.

**Comment by elaprime** [comment] 2021-07-20 16:39
[model2.zip](https://github.com/org-arl/UnderwaterAcoustics.jl/files/6849919/model2.zip)

**Comment by mchitre** [comment] 2021-07-20 16:49
OK, two problems, as far as I can tell:
1. The SSP depth entries are negative. They should be positive (z coordinate is negative underwater, but depth is positive).
2. The SSP should be defined between 0 and water depth (1482 m in your case), but is defined all the way to 12 km. I believe BELLHOP doesn't like that.

Fix these two issues and try again.

---

As for the inverted plot problem, I can't see any obvious reason. The data you are getting back is correct, I believe -- it's just the plot that has its axis inverted. What plotting backend are you using? Perhaps try in a fresh environment with not all those packages installed, to check if it is some conflict with some other packege that is causing it.

**Comment by elaprime** [comment] 2021-07-20 16:55
I'm not sure how to get around the depths, because that's the data I was given. The SSP is sampled at each of those depths as defined in depths2, which I negated and reversed to get the depth4. This was just an attempt to see if it would take those values. I wonder if my data is just not compatible with this model?

**Comment by mchitre** [comment] 2021-07-20 17:03
I just tried running BELLHOP with two changes to your SSP, and it works fine. So the model will work OK with your data.

Changes I made to get BELLHOP to run:
1. Negate all the depths (so they will all be positive numbers).
2. Remove the entries above 1482 m, and make the last entry be 1482 m. You have a 1500 m entry in there -- I changed it's depth to 1482 m since the SSP is flat beyond 1250 m. And I removed all entries beyond that.

**Comment by mchitre** [comment] 2021-07-20 17:41
Added #30 to improve error checking and documentation to flag problems like this before sending to BELLHOP.

**Comment by apatlpo** [comment] 2021-07-23 08:00
This issue deals with two problems at once and is hence a bit confusing.

I encounter the same up/down reversal for the Bellhop documentation example.
Should we start a dedicated issue about this?

**Comment by mchitre** [comment] 2021-07-23 09:00
@apatlpo agree. Opened new issue #31 to track this. Please post there, if you have steps/code I can use to reproduce the problem, including details of setup (ideally your Manifest.toml file).

**Comment by mchitre** [comment] 2021-07-23 09:01
@elaprime Other than the plot inversion issue, is this issue resolved? If so, we can close this one, and track the plot inversion issue in #31.

**Comment by elaprime** [comment] 2021-07-23 14:11
@mchitre I haven't got it working yet. I think one of our issues is that bellhop does not currently support range dependent SSP.

**Comment by mchitre** [comment] 2021-07-24 05:37
BELLHOP does support range dependent SSP. Just the `Bellhop()` model in `UnderwaterAcoustics.jl` doesn't yet support it (#15), but the support can be added.

The `RaySolver()` model in `UnderwaterAcoustics.jl`, however, does support range-dependent SSP.

**Closed** 2023-04-10 14:44 UTC
Labels: question
